name: Trigger JS Photo Gallery Test Runner

on:
  pull_request_target:
    branches: ["main"]

jobs:
  js_photo_gallery_test_runner:
    uses: developer-job-simulation/javascript-photo-gallery-tests/.github/workflows/main.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      head_sha: ${{ github.event.pull_request.head.sha }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }} 
